# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vclienteagregado.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_V_usuarioagregado(object):
    def setupUi(self, V_usuarioagregado):
        V_usuarioagregado.setObjectName("V_usuarioagregado")
        V_usuarioagregado.resize(402, 206)
        V_usuarioagregado.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(V_usuarioagregado)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_leyenda = QtWidgets.QLabel(self.centralwidget)
        self.lb_leyenda.setGeometry(QtCore.QRect(0, 30, 401, 101))
        self.lb_leyenda.setObjectName("lb_leyenda")
        V_usuarioagregado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(V_usuarioagregado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 21))
        self.menubar.setObjectName("menubar")
        V_usuarioagregado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(V_usuarioagregado)
        self.statusbar.setObjectName("statusbar")
        V_usuarioagregado.setStatusBar(self.statusbar)

        self.retranslateUi(V_usuarioagregado)
        QtCore.QMetaObject.connectSlotsByName(V_usuarioagregado)

    def retranslateUi(self, V_usuarioagregado):
        _translate = QtCore.QCoreApplication.translate
        V_usuarioagregado.setWindowTitle(_translate("V_usuarioagregado", "MainWindow"))
        self.lb_leyenda.setText(_translate("V_usuarioagregado", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">CLIENTE</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">AGREGADO</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">SATISFACTORIAMENTE</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    V_usuarioagregado = QtWidgets.QMainWindow()
    ui = Ui_V_usuarioagregado()
    ui.setupUi(V_usuarioagregado)
    V_usuarioagregado.show()
    sys.exit(app.exec_())
