# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vclienteeliminado.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_V_clienteeliminado(object):
    def setupUi(self, V_clienteeliminado):
        V_clienteeliminado.setObjectName("V_clienteeliminado")
        V_clienteeliminado.resize(402, 216)
        V_clienteeliminado.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(V_clienteeliminado)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_leyenda = QtWidgets.QLabel(self.centralwidget)
        self.lb_leyenda.setGeometry(QtCore.QRect(0, 30, 401, 101))
        self.lb_leyenda.setObjectName("lb_leyenda")
        V_clienteeliminado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(V_clienteeliminado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 21))
        self.menubar.setObjectName("menubar")
        V_clienteeliminado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(V_clienteeliminado)
        self.statusbar.setObjectName("statusbar")
        V_clienteeliminado.setStatusBar(self.statusbar)

        self.retranslateUi(V_clienteeliminado)
        QtCore.QMetaObject.connectSlotsByName(V_clienteeliminado)

    def retranslateUi(self, V_clienteeliminado):
        _translate = QtCore.QCoreApplication.translate
        V_clienteeliminado.setWindowTitle(_translate("V_clienteeliminado", "MainWindow"))
        self.lb_leyenda.setText(_translate("V_clienteeliminado", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">CLIENTE</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">ELIMINADO</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">SATISFACTORIAMENTE</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    V_clienteeliminado = QtWidgets.QMainWindow()
    ui = Ui_V_clienteeliminado()
    ui.setupUi(V_clienteeliminado)
    V_clienteeliminado.show()
    sys.exit(app.exec_())
