# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vclientenovalido.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_V_clientenovalido(object):
    def setupUi(self, V_clientenovalido):
        V_clientenovalido.setObjectName("V_clientenovalido")
        V_clientenovalido.resize(475, 243)
        V_clientenovalido.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(V_clientenovalido)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_leyenda = QtWidgets.QLabel(self.centralwidget)
        self.lb_leyenda.setGeometry(QtCore.QRect(0, 20, 471, 161))
        self.lb_leyenda.setObjectName("lb_leyenda")
        V_clientenovalido.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(V_clientenovalido)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        self.menubar.setObjectName("menubar")
        V_clientenovalido.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(V_clientenovalido)
        self.statusbar.setObjectName("statusbar")
        V_clientenovalido.setStatusBar(self.statusbar)

        self.retranslateUi(V_clientenovalido)
        QtCore.QMetaObject.connectSlotsByName(V_clientenovalido)

    def retranslateUi(self, V_clientenovalido):
        _translate = QtCore.QCoreApplication.translate
        V_clientenovalido.setWindowTitle(_translate("V_clientenovalido", "MainWindow"))
        self.lb_leyenda.setText(_translate("V_clientenovalido", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">CLIENTE NO VALIDO.</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">INTENTA CON UN REGISTRO</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">DADO PREVIAMENTE DE ALTA.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    V_clientenovalido = QtWidgets.QMainWindow()
    ui = Ui_V_clientenovalido()
    ui.setupUi(V_clientenovalido)
    V_clientenovalido.show()
    sys.exit(app.exec_())
