# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vclienteactualizado.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_V_clienteactualizado(object):
    def setupUi(self, V_clienteactualizado):
        V_clienteactualizado.setObjectName("V_clienteactualizado")
        V_clienteactualizado.resize(402, 206)
        V_clienteactualizado.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(V_clienteactualizado)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_leyenda = QtWidgets.QLabel(self.centralwidget)
        self.lb_leyenda.setGeometry(QtCore.QRect(0, 30, 401, 101))
        self.lb_leyenda.setObjectName("lb_leyenda")
        V_clienteactualizado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(V_clienteactualizado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 21))
        self.menubar.setObjectName("menubar")
        V_clienteactualizado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(V_clienteactualizado)
        self.statusbar.setObjectName("statusbar")
        V_clienteactualizado.setStatusBar(self.statusbar)

        self.retranslateUi(V_clienteactualizado)
        QtCore.QMetaObject.connectSlotsByName(V_clienteactualizado)

    def retranslateUi(self, V_clienteactualizado):
        _translate = QtCore.QCoreApplication.translate
        V_clienteactualizado.setWindowTitle(_translate("V_clienteactualizado", "MainWindow"))
        self.lb_leyenda.setText(_translate("V_clienteactualizado", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">CLIENTE</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">ACTUALIZADO</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">SATISFACTORIAMENTE</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    V_clienteactualizado = QtWidgets.QMainWindow()
    ui = Ui_V_clienteactualizado()
    ui.setupUi(V_clienteactualizado)
    V_clienteactualizado.show()
    sys.exit(app.exec_())
