# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vusuariovalido.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_V_usuariovalido(object):
    def setupUi(self, V_usuariovalido):
        V_usuariovalido.setObjectName("V_usuariovalido")
        V_usuariovalido.resize(475, 218)
        V_usuariovalido.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(V_usuariovalido)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_leyenda = QtWidgets.QLabel(self.centralwidget)
        self.lb_leyenda.setGeometry(QtCore.QRect(0, 30, 471, 101))
        self.lb_leyenda.setObjectName("lb_leyenda")
        V_usuariovalido.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(V_usuariovalido)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        self.menubar.setObjectName("menubar")
        V_usuariovalido.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(V_usuariovalido)
        self.statusbar.setObjectName("statusbar")
        V_usuariovalido.setStatusBar(self.statusbar)

        self.retranslateUi(V_usuariovalido)
        QtCore.QMetaObject.connectSlotsByName(V_usuariovalido)

    def retranslateUi(self, V_usuariovalido):
        _translate = QtCore.QCoreApplication.translate
        V_usuariovalido.setWindowTitle(_translate("V_usuariovalido", "MainWindow"))
        self.lb_leyenda.setText(_translate("V_usuariovalido", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">USUARIO VALIDO.</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">INGRESA DATOS EN LOS CAMPOS</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">RESTANTES Y PRESIONA GUARDAR.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    V_usuariovalido = QtWidgets.QMainWindow()
    ui = Ui_V_usuariovalido()
    ui.setupUi(V_usuariovalido)
    V_usuariovalido.show()
    sys.exit(app.exec_())
